// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import classNames from 'classnames/bind';

import { useSearchResultsActions } from '@sitecore-search/react';
import { Pagination } from '@sitecore-search/ui';

import styles from './styles.module.scss';

const cx = classNames.bind(styles);

type ReflectionSearchPaginationProps = {
  currentPage: number;
  totalPages: number;
};
const ReflectionSearchPagination = ({
  currentPage,
  totalPages,
}: ReflectionSearchPaginationProps) => {
  const { onPageNumberChange } = useSearchResultsActions();
  return (
    <div className={cx('reflection-search-pagination')}>
      {currentPage < totalPages && (
        <Pagination.Root
          currentPage={currentPage}
          defaultCurrentPage={1}
          totalPages={totalPages}
          onPageChange={(page) =>
            onPageNumberChange({
              page,
            })
          }
        >
          <Pagination.NextPage
            onClick={(_e) => _e.preventDefault()}
            className={cx('reflection-search-pagination__show-more', 'asc-btn asc-btn--outline')}
          >
            {'Show more'}
          </Pagination.NextPage>
        </Pagination.Root>
      )}
    </div>
  );
};
export default ReflectionSearchPagination;
