// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import { useSearchResultsActions } from '@sitecore-search/react';
import { Select, SortSelect } from '@sitecore-search/ui';

type ResultsPerPageProps = {
  defaultItemsPerPage: number;
};
const ResultsPerPage = ({ defaultItemsPerPage }: ResultsPerPageProps) => {
  const { onResultsPerPageChange } = useSearchResultsActions();
  return (
    <div>
      <label className="pr-1">Results Per Page</label>
      <Select.Root
        defaultValue={String(defaultItemsPerPage)}
        onValueChange={(v) =>
          onResultsPerPageChange({
            numItems: Number(v),
          })
        }
      >
        <Select.Trigger>
          <Select.SelectValue />
          <Select.Icon />
        </Select.Trigger>
        <Select.Content>
          <Select.Viewport className="p-1">
            <Select.SelectItem value="24">
              <SortSelect.OptionText>24</SortSelect.OptionText>
            </Select.SelectItem>
            <Select.SelectItem value="48">
              <SortSelect.OptionText>48</SortSelect.OptionText>
            </Select.SelectItem>
            <Select.SelectItem value="64">
              <SortSelect.OptionText>64</SortSelect.OptionText>
            </Select.SelectItem>
          </Select.Viewport>
        </Select.Content>
      </Select.Root>
    </div>
  );
};
export default ResultsPerPage;
