---
ID: "33c813fe-8763-49c8-8bdf-db961a8d6cd5"
Parent: "c1038672-9978-42f2-849d-f4979dc73312"
Template: "c1038672-9978-42f2-849d-f4979dc73312"
Path: /sitecore/templates/Feature/Intralox/Introduction/Introduction/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1bf77e85-b3b0-4ff3-a1ee-35a2ee04e86a"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260311T095547Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60e25671-288a-43f6-87eb-c7de40b2db63"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260329T113619Z
    - ID: "e3fdc5f3-9831-4818-ad8c-a39d33a7a312"
      Hint: MediaType
      Value: "{BEFDBBEA-75AB-4F7A-B906-F97061E79ECA}"
