---
ID: "2848fabc-222d-4aec-af64-75a2e1eb3176"
Parent: "82e94cb7-66c1-4489-a257-aaff9cd35b56"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Intralox/Global Locations/Rendering Parameters/Global Locations Parameters/Global Location Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260525T065444Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6c7ff8b-0a68-4b50-9ce8-c55bb57f0d30"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260525T065655Z
