---
ID: "31844de7-1ebd-444e-a046-14ab94c59c64"
Parent: "5d526da9-7bad-45a0-b3b4-ea02ca307da5"
Template: "5d526da9-7bad-45a0-b3b4-ea02ca307da5"
Path: /sitecore/templates/Feature/Customer Portal/UserActionTiles/UserActionTiles Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {FC5DF3F2-8DBC-4614-A369-B11B3232CFF3}
    {5D526DA9-7BAD-45A0-B3B4-EA02CA307DA5}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9ac051e7-c196-4f22-830f-6a90a6fcbb96"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "acfe5f23-5af7-4eb4-abdf-b4cd42eba496"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260509T113515Z
