---
ID: "1a2c5863-662e-4df4-8565-628aeda08fe1"
Parent: "8b72df70-dfa7-4b64-8d5c-ea558f729e8f"
Template: "8b72df70-dfa7-4b64-8d5c-ea558f729e8f"
Path: /sitecore/templates/Feature/Customer Portal/User Profile Menu/Rendering Parameters/UserProfileMenu Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9ab1ddc2-fb06-4a31-9ff7-bad56568b39d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251222T124658Z
