// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import type { SearchResultsInitialState, SearchResultsStoreState } from '@sitecore-search/react';
import type { ActionProp, ItemClickedAction } from '@sitecore-search/core';
import {
  WidgetDataType,
  useSearchResults,
  widget,
  useSearchResultsActions,
  FilterAnd,
} from '@sitecore-search/react';
import { useState, useEffect, useMemo } from 'react';

import Filters from '../../components/Filter';
import SearchFacets from '../../components/SearchFacets';
import SearchPagination from '../../components/SearchPagination';
import styles from './styles.module.scss';
import { MaterialIcon } from 'components/common/Icon/MaterialIcon';
import SortOrder from 'components/search/components/SortOrder';
import { ContentEntityModel } from 'components/search/models/content-entity';
import { useKeyphraseState } from '../../hooks/useKeyphraseState';
import { useFacetState } from '../../hooks/useFacetState';
import { useGatedVisibilityFilter } from '../../hooks/useGatedVisibilityFilter';
import { buildEmbargoFilter } from 'src/lib/sitecore-search/filters/embargo-filter';
import { MediaQueryConstants } from 'src/util/const/material';
import { useMediaQuery } from '@mui/material';

type RenderResultCardProps<T> = {
  item: T | null;
  index: number;
  onItemClick: ActionProp<ItemClickedAction>;
  isLoading: boolean;
};

type ArticlesSearchResultsProps<T = ContentEntityModel> = {
  defaultSortType: SearchResultsStoreState['sortType'];
  defaultPage?: SearchResultsStoreState['page'];
  defaultItemsPerPage?: SearchResultsStoreState['itemsPerPage'];
  defaultKeyphrase?: SearchResultsStoreState['keyphrase'];
  keyphrase?: SearchResultsStoreState['keyphrase'];
  renderResultCard: (props: RenderResultCardProps<T>) => React.JSX.Element;
  layoutMode?: 'grid' | 'row';
  showSortOrder?: boolean;
  emptyStateTitle?: string;
  emptyStateBody?: string;
  onResultsChange?: (data: { totalItems: number; keyphrase: string }) => void;
  showTermSummary?: boolean;
  filterPosition?: 'fullwidth' | 'sidebar' | 'listing' | 'none';
  displayFacetValueCount?: boolean;
  scrollTargetRef?: React.RefObject<HTMLElement | null>;
};
type InitialState = SearchResultsInitialState<
  'itemsPerPage' | 'keyphrase' | 'page' | 'sortType' | 'selectedFacets'
>;
export const SearchResultListingComponent = <T extends { id: string } = ContentEntityModel>({
  defaultSortType,
  defaultPage = 1,
  defaultKeyphrase = '',
  keyphrase: externalKeyphrase,
  defaultItemsPerPage = 24,
  renderResultCard,
  layoutMode = 'grid',
  showSortOrder = true,
  emptyStateTitle = 'No matches found',
  emptyStateBody = 'Try different search terms or adjust your filters.',
  onResultsChange,
  showTermSummary = true,
  filterPosition = 'fullwidth',
  displayFacetValueCount = false,
  scrollTargetRef,
}: ArticlesSearchResultsProps<T>) => {
  const [isFilterOpen, setIsFilterOpen] = useState(false);
  const { onClearFilters, onFacetClick } = useSearchResultsActions();
  const gatedVisibilityFilter = useGatedVisibilityFilter();
  const searchFilter = useMemo(
    () => new FilterAnd([gatedVisibilityFilter, buildEmbargoFilter()]),
    [gatedVisibilityFilter]
  );

  const {
    widgetRef,
    actions: { onKeyphraseChange, onItemClick },
    query: searchQuery,
    state: { page, sortType, itemsPerPage, keyphrase, selectedFacets },
    queryResult: {
      isFetching,
      isLoading,
      data: {
        total_item: totalItems = 0,
        sort: { choices: sortChoices = [] } = {},
        facet: facets = [],
        content: articles = [],
      } = {},
    },
  } = useSearchResults<T, InitialState>({
    query: (query) => {
      query.getRequest().setSearchFilter(searchFilter);
    },
    state: {
      sortType: defaultSortType,
      page: defaultPage,
      itemsPerPage: defaultItemsPerPage,
      keyphrase: defaultKeyphrase,
      selectedFacets: [], // Will be restored from query string after facets load
    },
  });

  // Reactively update the search filter (gated + embargo) when session loads
  useEffect(() => {
    searchQuery.getRequest().setSearchFilter(searchFilter);
  }, [searchFilter, searchQuery]);

  // Manage keyphrase/term state
  useKeyphraseState({
    externalKeyphrase,
    currentKeyphrase: keyphrase,
    onKeyphraseChange,
  });

  // Manage facet state (restoration and query string sync)
  useFacetState({
    keyphrase,
    selectedFacets,
    facets,
    isLoading,
    isFetching,
    onFacetClick,
  });

  const handleReset = () => {
    onClearFilters();
    setIsFilterOpen(false);
  };

  const handleApplyFilters = () => {
    setIsFilterOpen(false);
  };

  // Notify parent component of results data changes
  useEffect(() => {
    if (onResultsChange && !isLoading && !isFetching) {
      onResultsChange({
        totalItems,
        keyphrase: keyphrase || '',
      });
    }
  }, [totalItems, keyphrase, isLoading, isFetching, onResultsChange]);

  const totalPages = Math.ceil(totalItems / itemsPerPage);

  const isMobile = useMediaQuery(MediaQueryConstants.Mobile);

  const hasFiltersShowing = (selectedFacets?.length ?? 0) > 0 || Boolean(keyphrase);

  return (
    <div ref={widgetRef} className={styles['search-result-listing']}>
      {filterPosition === 'fullwidth' && (
        <div>
          <Filters currentKeyphrase={keyphrase} showTermSummary={showTermSummary} />
        </div>
      )}

      {/* Main Content */}
      <div className={styles['search-result-listing__content']}>
        {/* Sidebar with Filters */}
        <aside
          className={`${styles['search-result-listing__sidebar']} ${isFilterOpen ? styles['search-result-listing__sidebar--open'] : ''}`}
        >
          <div className="flex justify-between mt-8 md:mt-0 items-center">
            <button
              className={styles['search-result-listing__filter-toggle']}
              onClick={() => setIsFilterOpen(!isFilterOpen)}
              aria-expanded={isFilterOpen}
            >
              <MaterialIcon name="filterList" />
              Filter
            </button>
            {(totalItems > 0 || isLoading || isFetching) && isMobile && showSortOrder && (
              <SortOrder options={sortChoices} selected={sortType} />
            )}
          </div>
          {(totalItems > 0 || isLoading || isFetching) && isMobile && showSortOrder && (
            <div
              className={`${styles['search-result-listing__sort-container']} ${
                filterPosition === 'listing'
                  ? styles['search-result-listing__sort-container--with-filters']
                  : ''
              }`}
            >
              {filterPosition === 'listing' && (
                <Filters currentKeyphrase={keyphrase} showTermSummary={showTermSummary} />
              )}
            </div>
          )}

          <div className={styles['search-result-listing__facets-container']}>
            <div className={styles['search-result-listing__facets-header']}>
              <h2>Filters</h2>
              <button
                className={styles['search-result-listing__facets-close']}
                onClick={() => setIsFilterOpen(false)}
                aria-label="Close filters"
              >
                <MaterialIcon name="close" />
              </button>
            </div>
            <SearchFacets facets={facets} displayFacetValueCount={displayFacetValueCount} />
            <div className={styles['search-result-listing__facets-actions']}>
              <button
                className={styles['search-result-listing__reset-button']}
                onClick={handleReset}
              >
                RESET
              </button>
              <button
                className={styles['search-result-listing__apply-button']}
                onClick={handleApplyFilters}
              >
                APPLY FILTERS
              </button>
            </div>
          </div>
        </aside>

        {/* Main Content Area */}
        <main className={styles['search-result-listing__main']}>
          <>
            {totalItems > 0 || isLoading || isFetching ? (
              <>
                {!isMobile && showSortOrder && (
                  <div
                    className={`${styles['search-result-listing__sort-container']} ${
                      filterPosition === 'listing'
                        ? styles['search-result-listing__sort-container--with-filters']
                        : ''
                    } ${
                      hasFiltersShowing
                        ? styles['search-result-listing__sort-container--filters-showing']
                        : ''
                    }`}
                  >
                    {filterPosition === 'listing' && (
                      <Filters currentKeyphrase={keyphrase} showTermSummary={showTermSummary} />
                    )}
                    <SortOrder options={sortChoices} selected={sortType} />
                  </div>
                )}
                {/* Results Grid */}
                <div
                  className={`${styles['search-result-listing__grid']} ${
                    layoutMode === 'row' ? styles['search-result-listing__grid--row'] : ''
                  }`}
                >
                  {(isLoading || isFetching ? [...Array(itemsPerPage)] : articles).map(
                    (item, index) =>
                      renderResultCard({
                        item: isLoading || isFetching ? null : (item as T),
                        index,
                        onItemClick,
                        isLoading: isLoading || isFetching,
                      })
                  )}
                </div>

                {/* Pagination */}
                {!isLoading && !isFetching && totalItems > 0 && (
                  <div className={styles['search-result-listing__pagination-container']}>
                    <SearchPagination
                      currentPage={page}
                      totalPages={totalPages}
                      scrollTargetRef={scrollTargetRef}
                    />
                  </div>
                )}
              </>
            ) : (
              <div className={styles['search-result-listing__empty-state']}>
                <h3>{emptyStateTitle}</h3>
                <p>{emptyStateBody}</p>
              </div>
            )}
          </>
        </main>
      </div>
    </div>
  );
};
const SearchResultListingWidget = widget(
  SearchResultListingComponent,
  WidgetDataType.SEARCH_RESULTS,
  'content'
);
export default SearchResultListingWidget;
