// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import type { SearchResponseSortChoice } from '@sitecore-search/data';
import { useSearchResultsActions } from '@sitecore-search/react';
import { SortSelect } from '@sitecore-search/ui';
import styles from './SortOrder.module.scss';
import { MaterialIcon } from 'components/common/Icon/MaterialIcon';

type SortOrderProps = {
  options: Array<SearchResponseSortChoice>;
  selected: string;
};
const SortOrder = ({ options, selected }: SortOrderProps) => {
  const { onSortChange } = useSearchResultsActions();

  return (
    <div className={styles['sort-order']}>
      <span className={styles['sort-order__label']}>Sort by:</span>
      <SortSelect.Root value={selected} onValueChange={onSortChange}>
        <SortSelect.Trigger>
          <SortSelect.SelectValue placeholder="Select sort order" />
          <MaterialIcon name="KeyboardArrowDownOutlined" />
        </SortSelect.Trigger>
        <SortSelect.Content className="bg-brand-gray-50 dark:bg-gray-700 shadow-[2px_2px_4px_#CFCFCF] z-[100] absolute right-[-100px] left-unset top-8  min-w-[250px] rounded-md overflow-hidden">
          <SortSelect.Viewport>
            {options.map((option: SearchResponseSortChoice) => (
              <SortSelect.Option
                value={option}
                key={option.name}
                className="flex items-center leading-none cursor-pointer select-none whitespace-no-wrap h-6 p-4 hover:bg-brand-blue-500 dark:hover:bg-gray-100 hover:text-white dark:hover:text-gray-700 data-[state=checked]:text-white data-[state=checked]:bg-brand-blue-800 focus:outline-0"
              >
                <SortSelect.OptionText>{option.label}</SortSelect.OptionText>
              </SortSelect.Option>
            ))}
          </SortSelect.Viewport>
        </SortSelect.Content>
      </SortSelect.Root>
    </div>
  );
};
export default SortOrder;
