---
ID: "2b645595-312e-4292-84de-0f52dfcc6297"
Parent: "0087312f-4192-4fb0-a9a0-4df294b12018"
Template: "0087312f-4192-4fb0-a9a0-4df294b12018"
Path: /sitecore/templates/Feature/Intralox/Tabs/Tab Item/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "88fbfc23-9e93-46ac-9381-d61cee628c18"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260217T085120Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "336b2d2f-c1fe-4b7c-bb95-2d1e0268b7eb"
    - ID: "98d56d32-e993-4b61-a13e-39012938c9c1"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260331T101646Z
