// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries
} from "@sitecore-content-sdk/nextjs/codegen";
// end of built-in imports

import componentMap from ".sitecore/component-map";
import OktaPasswordResetWidget from "@/components/core/Auth/octa-widget/OktaResetPasswordWidget";
import LanguageSwitcher from "@/components/layout/Header/Language";
import {
  sendLoginEvent,
  sendRegisterEvent,
  sendResetPasswordEvent
} from "@/lib/CDPEvents";
import { OktaAuth } from "@okta/okta-auth-js";
import { useOktaAuth } from "@okta/okta-react";
import { event, pageView } from "@sitecore-cloudsdk/events/browser";
import {
  AppPlaceholder,
  CdpHelper,
  Link,
  NextImage,
  RichText,
  Text,
  useSitecore,
  withDatasourceCheck
} from "@sitecore-content-sdk/nextjs";
import OktaSignInWidget from "components/core/Auth/octa-widget/OktaSignInWidget";
import ChevronRightIcon from "components/shared/icons/ChevronRightIcon";
import { getDeviceType as getDeviceType_4804c755ae919bb21ebeb6f8c2a80c20a9a92ffa } from "lib/device-utils";
import { logGTMLogout } from "lib/gtm";
import { languages, useLanguage } from "lib/language-context";
import { getOktaAuthConfig, isOktaConfigured } from "lib/okta-config";
import { getOktaAuth } from "lib/oktaAuth";
import Head from "next/head";
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import Script from "next/script";
import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState
} from "react";
import config from "sitecore.config";
import OktaSignInWidget_16a6fa2369b4044a08a60440810a3f48f81d6fe0 from "src/components/core/Auth/octa-widget/OktaSignInWidget";
import { AuthDefaultVariant } from "src/components/core/Auth/variants/AuthDefault.variant";
import { FeaturedContentDefaultVariant } from "src/components/core/FeaturedContent/variants/FeaturedContentDefault.variant";
import Header from "src/components/layout/Header/Header";
import Help from "src/components/layout/Header/Help";

import SearchBar from "src/components/layout/Header/SearchBar";
import UserMenu from "src/components/layout/Header/UserMenu";
import Sidebar from "src/components/layout/Sidebar/Sidebar";
import ErrorMessage from "src/components/shared/error-message/ErrorMessage";
import Icon from "src/components/shared/icons/Icon";
import LoadingSkeleton from "src/components/shared/loading-skeleton/LoadingSkeleton";
import SuccessMessage from "src/components/shared/success-message/SuccessMessage";
import Toast from "src/components/shared/toast/Toast";
import {
  AUTH_ERROR_MESSAGES,
  AUTH_SUCCESS_MESSAGES,
  TEST_CASE_DATA_IDS
} from "src/helpers/enums";
import useDomMutationRender from "src/helpers/usePageHeight";
import { getDeviceType } from "src/lib/device-utils";
import { logGTMLoginPageView, logGTMRegisterPageView } from "src/lib/gtm";
import client from "src/lib/sitecore-client";

const importMap = [
  {
    module: "react",
    exports: [
      { name: "createContext", value: createContext },
      { name: "useContext", value: useContext },
      { name: "useState", value: useState },
      { name: "useCallback", value: useCallback },
      { name: "useEffect", value: useEffect },
      { name: "useRef", value: useRef },
      { name: "useMemo", value: useMemo },
      { name: "default", value: React }
    ]
  },
  {
    module: "@sitecore-content-sdk/nextjs",
    exports: [
      { name: "Link", value: Link },
      { name: "Text", value: Text },
      { name: "AppPlaceholder", value: AppPlaceholder },
      { name: "RichText", value: RichText },
      { name: "NextImage", value: NextImage },
      { name: "useSitecore", value: useSitecore },
      { name: "CdpHelper", value: CdpHelper },
      { name: "withDatasourceCheck", value: withDatasourceCheck }
    ]
  },
  {
    module: "src/components/shared/toast/Toast",
    exports: [{ name: "default", value: Toast }]
  },
  {
    module: "src/components/shared/icons/Icon",
    exports: [{ name: "default", value: Icon }]
  },
  {
    module: "next/link",
    exports: [
      { name: "default", value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 }
    ]
  },
  {
    module: ".sitecore/component-map",
    exports: [{ name: "default", value: componentMap }]
  },
  {
    module: "src/components/layout/Sidebar/Sidebar",
    exports: [{ name: "default", value: Sidebar }]
  },
  {
    module: "src/components/layout/Header/Header",
    exports: [{ name: "default", value: Header }]
  },
  {
    module: "next/navigation",
    exports: [
      { name: "usePathname", value: usePathname },
      { name: "useRouter", value: useRouter },
      { name: "useSearchParams", value: useSearchParams }
    ]
  },
  {
    module: "@okta/okta-react",
    exports: [{ name: "useOktaAuth", value: useOktaAuth }]
  },
  {
    module: "lib/gtm",
    exports: [{ name: "logGTMLogout", value: logGTMLogout }]
  },
  {
    module: "lib/okta-config",
    exports: [
      { name: "getOktaAuthConfig", value: getOktaAuthConfig },
      { name: "isOktaConfigured", value: isOktaConfigured }
    ]
  },
  {
    module: "@okta/okta-auth-js",
    exports: [{ name: "OktaAuth", value: OktaAuth }]
  },
  {
    module: "lib/language-context",
    exports: [
      { name: "useLanguage", value: useLanguage },
      { name: "languages", value: languages }
    ]
  },
  {
    module: "src/components/layout/Header/SearchBar",
    exports: [{ name: "default", value: SearchBar }]
  },
  {
    module: "src/components/layout/Header/Notification",
    exports: [{ name: "default", value: Notification }]
  },
  {
    module: "src/components/layout/Header/UserMenu",
    exports: [{ name: "default", value: UserMenu }]
  },
  {
    module: "src/components/layout/Header/LanguageSwitcher",
    exports: [{ name: "default", value: LanguageSwitcher }]
  },
  {
    module: "src/components/layout/Header/Help",
    exports: [{ name: "default", value: Help }]
  },
  {
    module: "next/head",
    exports: [{ name: "default", value: Head }]
  },
  {
    module: "next/script",
    exports: [{ name: "default", value: Script }]
  },
  {
    module: "src/helpers/enums",
    exports: [
      { name: "TEST_CASE_DATA_IDS", value: TEST_CASE_DATA_IDS },
      { name: "AUTH_ERROR_MESSAGES", value: AUTH_ERROR_MESSAGES },
      { name: "AUTH_SUCCESS_MESSAGES", value: AUTH_SUCCESS_MESSAGES }
    ]
  },
  {
    module:
      "src/components/core/FeaturedContent/variants/FeaturedContentDefault.variant",
    exports: [
      {
        name: "FeaturedContentDefaultVariant",
        value: FeaturedContentDefaultVariant
      }
    ]
  },
  {
    module: "src/helpers/usePageHeight",
    exports: [{ name: "default", value: useDomMutationRender }]
  },
  {
    module: "components/shared/icons/ChevronRightIcon",
    exports: [{ name: "default", value: ChevronRightIcon }]
  },
  {
    module: "src/components/core/Auth/variants/AuthDefault.variant",
    exports: [{ name: "AuthDefaultVariant", value: AuthDefaultVariant }]
  },
  {
    module: "lib/oktaAuth",
    exports: [{ name: "getOktaAuth", value: getOktaAuth }]
  },
  {
    module: "src/components/shared/loading-skeleton/LoadingSkeleton",
    exports: [{ name: "default", value: LoadingSkeleton }]
  },
  {
    module: "components/core/Auth/octa-widget/OktaPasswordResetWidget",
    exports: [{ name: "default", value: OktaPasswordResetWidget }]
  },
  {
    module: "src/components/shared/error-message/ErrorMessage",
    exports: [{ name: "default", value: ErrorMessage }]
  },
  {
    module: "src/components/shared/success-message/SuccessMessage",
    exports: [{ name: "default", value: SuccessMessage }]
  },
  {
    module: "components/CDP/CDPEvents",
    exports: [
      { name: "sendResetPasswordEvent", value: sendResetPasswordEvent },
      { name: "sendLoginEvent", value: sendLoginEvent }
    ]
  },
  {
    module: "components/core/Auth/octa-widget/OktaSignInWidget",
    exports: [{ name: "default", value: OktaSignInWidget }]
  },
  {
    module: "src/lib/gtm",
    exports: [
      { name: "logGTMRegisterPageView", value: logGTMRegisterPageView },
      { name: "logGTMLoginPageView", value: logGTMLoginPageView }
    ]
  },
  {
    module: "src/components/CDP/CDPEvents",
    exports: [{ name: "sendRegisterEvent", value: sendRegisterEvent }]
  },
  {
    module: "src/components/core/Auth/octa-widget/OktaSignInWidget",
    exports: [
      {
        name: "default",
        value: OktaSignInWidget_16a6fa2369b4044a08a60440810a3f48f81d6fe0
      }
    ]
  },
  {
    module: "src/lib/sitecore-client",
    exports: [{ name: "default", value: client }]
  },
  {
    module: "@sitecore-cloudsdk/events/browser",
    exports: [
      { name: "pageView", value: pageView },
      { name: "event", value: event }
    ]
  },
  {
    module: "sitecore.config",
    exports: [{ name: "default", value: config }]
  },
  {
    module: "src/lib/device-utils",
    exports: [{ name: "getDeviceType", value: getDeviceType }]
  },
  {
    module: "lib/device-utils",
    exports: [
      {
        name: "getDeviceType",
        value: getDeviceType_4804c755ae919bb21ebeb6f8c2a80c20a9a92ffa
      }
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
