---
ID: "a58ed243-0258-4196-a4e5-ac321454b637"
Parent: "0bfc7d13-ffc4-4b7d-a5c2-ac85e6ea1b62"
Template: "0bfc7d13-ffc4-4b7d-a5c2-ac85e6ea1b62"
Path: /sitecore/templates/Project/Customer App/Page Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0BFC7D13-FFC4-4B7D-A5C2-AC85E6EA1B62}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "62fc854f-9e5c-425f-bdab-1999af43da81"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251120T121954Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5d304f4c-ec2b-4d0c-a79c-0609cf07b410"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251120T122002Z
