---
ID: "3c2edc86-0377-466c-87c3-98b3e5477dc4"
Parent: "1fd62d7e-fae1-43ad-b913-cacdf98ac4e0"
Template: "1fd62d7e-fae1-43ad-b913-cacdf98ac4e0"
Path: /sitecore/templates/Foundation/Intralox/Video Type/Video Item/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a4b4ad6b-f128-453c-b14e-7e8122845098"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260306T084801Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "5c97f7c9-5590-413d-8274-d1f693893a7c"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bd6db1c2-c224-4a84-9c9a-4964be23bb2f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260306T085317Z
