---
ID: "d5f9ea26-387c-4f4c-a5c3-e38e61992a9c"
Parent: "24c8d882-5f30-4e73-aaee-f5b6b46b7368"
Template: "24c8d882-5f30-4e73-aaee-f5b6b46b7368"
Path: /sitecore/templates/Feature/Intralox/InfoBox/InfoBox/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "322d7e4d-6395-4314-bca2-223c3c4fda36"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1c9f6b45-0e8d-4dfa-92b0-8afeb0e541c7"
      Hint: Context
      Value: "{7CEF72B0-0A21-4A54-9347-F3828D394BCF}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260311T095547Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d95ed9b0-1e1b-49bf-ad04-d23593e4a6e0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260331T130859Z
