---
ID: "46934b41-ada5-4131-a3eb-3ff579dc0933"
Parent: "1f3248bd-0e88-418d-858b-c3a60c3ff85a"
Template: "1f3248bd-0e88-418d-858b-c3a60c3ff85a"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Products/Accessories/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260511T094150Z
    - ID: "46107cb4-da05-4caa-95b8-5b1a0e466f36"
      Hint: Technology
      Value: "{5EAE3A7F-C63A-4A5E-9D11-4B9B39356E4B}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30e66d62-a009-466e-a9e1-f3800396f5ad"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260603T110133Z
