---
ID: "0951367b-3581-4ead-9818-6461ec040af2"
Parent: "efd97d93-e1eb-407d-81fa-f51afb9dd87f"
Template: "efd97d93-e1eb-407d-81fa-f51afb9dd87f"
Path: /sitecore/templates/Project/Customer App/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {EFD97D93-E1EB-407D-81FA-F51AFB9DD87F}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "490f9a6f-e845-40d4-8548-6466e3c1b451"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251120T121955Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0c7a26f8-412b-4732-a582-baca5cbcce50"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\suneel.joshi@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251120T122002Z
