---
ID: "7e5b74b0-76cf-4383-89c5-d32195bee279"
Parent: "63b4babb-055d-405f-b721-4a5be47667c9"
Template: "63b4babb-055d-405f-b721-4a5be47667c9"
Path: /sitecore/templates/Foundation/Intralox/Alert Info/Alert Info/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 255
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "36799776-0a7f-43a4-ada7-1f155f97e9ee"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260528T091124Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b566430a-c2c4-4277-95d8-94e485692027"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260528T091855Z
