---
ID: "f80ebc8f-40f0-48d6-9441-611c4b8586d7"
Parent: "c5862026-a76b-4ee9-bec4-5450b2f37f61"
Template: "c5862026-a76b-4ee9-bec4-5450b2f37f61"
Path: /sitecore/templates/Feature/Intralox/Media Tile/Links Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{197FEEE8-00AC-422C-917B-4BFC00CBF40B}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8d632d29-ad7b-42ed-a770-e28ad6940c24"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260306T123942Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4833fef4-4e9d-448f-8a89-c39ad9b7c094"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260306T124033Z
