---
ID: "e69072db-42dc-4e89-92e5-48da230276fc"
Parent: "cb311034-ac20-49a3-9e49-58b369366395"
Template: "cb311034-ac20-49a3-9e49-58b369366395"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Case Study Page/Case Study Listing Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3ADFB01B-06CB-4DDF-815F-479554F6202F}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "f4a0b60a-1efb-4d3f-8adb-9a032d3751e8"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260414T075538Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "875d7092-88c9-4d7a-83df-3248d77ae6ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260415T115958Z
