---
ID: "8739729e-5cac-4862-b9a1-3c595267fd41"
Parent: "9b69e59d-6534-4d62-91e8-fcfe4c4aef80"
Template: "9b69e59d-6534-4d62-91e8-fcfe4c4aef80"
Path: /sitecore/templates/Feature/Customer Portal/PortalShell SideNav/Sub Navigation Item/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9B69E59D-6534-4D62-91E8-FCFE4C4AEF80}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ecb95f23-b0b4-4304-a942-7315538e6842"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0b35e1ea-edfc-410b-885f-b8ddb39394c4"
      Hint: Title
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260303T085549Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dd77812c-08c5-449c-8216-4f84b81ecfab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260303T091114Z
