// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import { useSearchResultsActions, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import styles from './styles.module.scss';

type SelectedFacet = {
  facetId: string;
  facetLabel?: string;
  valueLabel?: string;
  min?: number;
  max?: number;
};

const buildRangeLabel = (min: number | undefined, max: number | undefined): string => {
  return typeof min === 'undefined'
    ? `< $${max}`
    : typeof max === 'undefined'
      ? ` > $${min}`
      : `$${min} - $${max}`;
};
const buildFacetLabel = (selectedFacet: SelectedFacet) => {
  if ('min' in selectedFacet || 'max' in selectedFacet) {
    return `${buildRangeLabel(selectedFacet.min, selectedFacet.max)}`;
  }
  return `${selectedFacet.valueLabel || ''}`;
};
const Filters = ({
  currentKeyphrase,
  showTermSummary = true,
}: {
  currentKeyphrase: string;
  showTermSummary?: boolean;
}) => {
  const selectedFacetsFromApi = useSearchResultsSelectedFilters();
  const { onRemoveFilter, onClearFilters } = useSearchResultsActions();

  const hasKeyphrase = currentKeyphrase && currentKeyphrase.trim().length > 0;
  const hasFilters = selectedFacetsFromApi.length > 0;

  if (!hasKeyphrase && !hasFilters) {
    return <></>;
  }

  return (
    <div className={styles['filter']}>
      {hasKeyphrase && showTermSummary && (
        <div className={styles['filter__header']}>
          <h3 className={styles['filter__title']}>
            Search results for: <span>&quot;{currentKeyphrase}&quot;</span>
          </h3>
        </div>
      )}
      {hasFilters && (
        <div className={styles['filter__active-filters']}>
          {selectedFacetsFromApi.map((selectedFacet) => (
            <button
              key={`${selectedFacet.facetId}${selectedFacet.facetLabel}${selectedFacet.valueLabel}`}
              onClick={() => onRemoveFilter(selectedFacet)}
              className={styles['filter__filter-tag']}
            >
              {buildFacetLabel(selectedFacet)}
            </button>
          ))}
          <button onClick={onClearFilters} className={styles['filter__clear-button']}>
            Clear all
          </button>
        </div>
      )}
    </div>
  );
};
export default Filters;
