---
ID: "74932a37-55c1-418f-a96c-dd79daef79f2"
Parent: "8439bc75-6075-4cd7-a715-7c3e8cfd3b2f"
Template: "8439bc75-6075-4cd7-a715-7c3e8cfd3b2f"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Products/Tools/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260511T094215Z
    - ID: "46107cb4-da05-4caa-95b8-5b1a0e466f36"
      Hint: Technology
      Value: "{5EAE3A7F-C63A-4A5E-9D11-4B9B39356E4B}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "94c7b1b7-5421-4017-a243-58511dc265a7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260603T110114Z
