---
ID: "0e556c4e-fc51-4e69-9bad-07ebe3821d32"
Parent: "7f9f2bd1-07f7-4d75-b92a-09b9eb9a3afc"
Template: "7f9f2bd1-07f7-4d75-b92a-09b9eb9a3afc"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {A7FDBEDC-8E77-4D7D-8E11-1DFF8399AE00}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "da9bf32e-3490-4fcf-85c7-065560ee89ba"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260210T090329Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9249392e-9c7b-42ff-b598-46538237988e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260210T090335Z
