// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 14:55:19 GMT-0500 (Eastern Standard Time)

import type { ChangeEvent } from 'react';
import { useCallback, useMemo, useRef, useState, useEffect } from 'react';
import { useI18n } from 'next-localization';

import type { PreviewSearchInitialState } from '@sitecore-search/react';
import {
  WidgetDataType,
  usePreviewSearch,
  widget,
  FilterAnyOf,
  FilterAnd,
} from '@sitecore-search/react';
import { ArticleCard, Presence, PreviewSearch } from '@sitecore-search/ui';
import SuggestionBlock from 'components/search/components/SuggestionBlock';
import styles from './styles.module.scss';
import { MaterialIcon } from 'components/common/Icon/MaterialIcon';
import { ContentEntityModel } from 'components/search/models/content-entity';
import Skeleton from '@mui/material/Skeleton';
import classNames from 'classnames/bind';
import {
  useSearchWithinSite,
  type SearchWithinSite,
} from 'components/search/hooks/useSearchWithinSite';
import { useGatedVisibilityFilter } from 'components/search/hooks/useGatedVisibilityFilter';
import { buildEmbargoFilter } from 'src/lib/sitecore-search/filters/embargo-filter';
const cx = classNames.bind(styles);

const GlobalSearchBarStatics = {
  placeholder: 'Search for policies, news, benefits...',
  clearSearchAriaLabel: 'Clear search',
  submitSearchAriaLabel: 'Submit search',
  searchingAllSiteName: 'OurAscension',
  searchAllInstead: 'Search all instead.',
  searchSiteInstead: 'Search',
  searchSiteInsteadSuffix: 'instead.',
  recentSuggestionsTitle: 'Recent',
  trendingSuggestionsTitle: 'Trending',
  noSuggestionsFound: 'No suggestions found for',
  searchingPrefix: 'Searching',
};

type InitialState = PreviewSearchInitialState<'keyphrase' | 'itemsPerPage' | 'suggestionsList'>;

const getResultTypeIcon = (article: ContentEntityModel): string => {
  const type = article.result_type || 'default';

  const iconMap: Record<string, string> = {
    'Reflection Listing': 'format quote',
    'news article': 'newspaper',
    'directory entry': 'link',
    'site page': 'article',
    default: 'article',
  };

  return iconMap[type.toLowerCase()] || iconMap.default;
};

interface PreviewSearchBarProps {
  defaultItemsPerPage: number | 6;
  placeholder?: string;
  inputClassName?: string;
  keyphrase?: string;
  /**
   * Controls whether recent history suggestions are shown when there is no input.
   * Defaults to true.
   */
  showRecentSuggestions?: boolean;
  /**
   * Controls whether trending terms suggestions are shown when there is no input.
   * Defaults to true.
   */
  showTrendingSuggestions?: boolean;
  /**
   * Controls whether the "Searching {site}" scoping bar is shown.
   * When enabled, preview search results are filtered by the matched site's association tags.
   * Defaults to true.
   */
  showSearchWithin?: boolean;

  /**
   * An optional custom redirection handler that will be called when the user clicks on an article.
   * You can use your own redirection logic here, or any other side effect.
   * Examples
   * * (article: Article) => history.push(`/search?q=${article.id}`);
   * * (article: Article) => window.location.href = `/search?q=${article.id}`;
   * * (article: Article) => setRoute(`/custom/search/endpoint?q=${article.id}`);
   * @param article The article that was clicked.
   */
  itemRedirectionHandler?: (article: ContentEntityModel) => void;

  /**
   * An optional custom submit handler that will be called when the user submits the form by pressing the enter key.
   * You can use your own submit logic here, or any other side effect.
   * Most common use case is to redirect the user to a custom search page with the query string.
   * Examples
   * * (query: string) => history.push(`/search?q=${query}`);
   * * (query: string) => window.location.href = `/search?q=${query}`;
   * * (query: string) => setRoute(`/custom/search/endpoint?q=${query}`);
   * @param query The query string that was submitted.
   * @param filterParams Optional pre-encoded query string of facet filter params (e.g. `f.site_area=St.+Vincent`).
   *   Populated when SearchWithin is active so the search page can pre-apply the site filters.
   */
  submitRedirectionHandler?: (query: string, filterParams?: string) => void;
}

interface SearchBarInnerProps extends Omit<PreviewSearchBarProps, 'showSearchWithin'> {
  matchedSite: SearchWithinSite | null;
  isSearchingWithin: boolean;
  onToggleSearchWithin: () => void;
  onInputChange?: (value: string) => void;
  searchWithinQueryString?: string;
}

const SearchBarInner = ({
  defaultItemsPerPage = 6,
  placeholder,
  inputClassName,
  keyphrase,
  showRecentSuggestions = true,
  showTrendingSuggestions = true,
  itemRedirectionHandler,
  submitRedirectionHandler,
  matchedSite,
  isSearchingWithin,
  onToggleSearchWithin,
  onInputChange,
  searchWithinQueryString,
}: SearchBarInnerProps) => {
  const { t } = useI18n();
  const placeholderText =
    placeholder || t('GlobalSearchBarPlaceholder') || GlobalSearchBarStatics.placeholder;
  const clearSearchAriaLabel =
    t('GlobalSearchBarClearAriaLabel') || GlobalSearchBarStatics.clearSearchAriaLabel;
  const submitSearchAriaLabel =
    t('GlobalSearchBarSubmitAriaLabel') || GlobalSearchBarStatics.submitSearchAriaLabel;
  const searchingAllSiteName =
    t('GlobalSearchBarAllSiteName') || GlobalSearchBarStatics.searchingAllSiteName;
  const searchAllInstead =
    t('GlobalSearchBarSearchAllInstead') || GlobalSearchBarStatics.searchAllInstead;
  const searchSiteInstead =
    t('GlobalSearchBarSearchSiteInstead') || GlobalSearchBarStatics.searchSiteInstead;
  const searchSiteInsteadSuffix =
    t('GlobalSearchBarSearchSiteInsteadSuffix') || GlobalSearchBarStatics.searchSiteInsteadSuffix;
  const recentSuggestionsTitle =
    t('GlobalSearchBarRecentTitle') || GlobalSearchBarStatics.recentSuggestionsTitle;
  const trendingSuggestionsTitle =
    t('GlobalSearchBarTrendingTitle') || GlobalSearchBarStatics.trendingSuggestionsTitle;
  const noSuggestionsFound =
    t('GlobalSearchBarNoSuggestionsFound') || GlobalSearchBarStatics.noSuggestionsFound;
  const searchingPrefix =
    t('GlobalSearchBarSearchingPrefix') || GlobalSearchBarStatics.searchingPrefix;

  const gatedVisibilityFilter = useGatedVisibilityFilter();
  const searchFilter = useMemo(
    () => new FilterAnd([gatedVisibilityFilter, buildEmbargoFilter()]),
    [gatedVisibilityFilter]
  );

  const filterTags = isSearchingWithin
    ? matchedSite?.site_level_association_tags?.[0]?.title?.value
    : null;
  const isFiltering = !!filterTags?.length;
  const activeFilterParams = isSearchingWithin ? searchWithinQueryString : undefined;

  const {
    widgetRef,
    actions: { onItemClick, onKeyphraseChange },
    state: { keyphrase: widgetKeyphrase },
    query: searchQuery,
    queryResult,
    queryResult: {
      isFetching,
      isLoading,
      data: {
        suggestion: {
          recent_history: recentHistorySuggestions = [],
          trending_terms: trendingTermsSuggestions = [],
        } = {},
      } = {},
    },
  } = usePreviewSearch<ContentEntityModel, InitialState>({
    state: {
      keyphrase: keyphrase || '',
      suggestionsList: [
        { suggestion: 'recent_history', max: 3 },
        { suggestion: 'trending_terms', max: 5 },
      ],
      itemsPerPage: defaultItemsPerPage,
    },
    query: (query) => {
      if (isFiltering && filterTags?.length) {
        query
          .getRequest()
          .setSearchFilter(
            new FilterAnd([new FilterAnyOf('site_area_tags', [filterTags]), searchFilter])
          );
      } else {
        query.getRequest().setSearchFilter(searchFilter);
      }
    },
  });

  useEffect(() => {
    const request = searchQuery.getRequest();
    if (isFiltering && filterTags?.length) {
      request.setSearchFilter(
        new FilterAnd([new FilterAnyOf('site_area_tags', [filterTags]), searchFilter])
      );
    } else {
      request.setSearchFilter(searchFilter);
    }
  }, [isFiltering, filterTags, searchQuery, searchFilter]);

  const loading = isLoading || isFetching;
  const formRef = useRef<HTMLFormElement>(null);
  const [inputValue, setInputValue] = useState<string>(keyphrase || '');
  const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  useEffect(() => {
    if (keyphrase !== undefined && keyphrase !== inputValue) {
      setInputValue(keyphrase);
      onKeyphraseChange({
        keyphrase: keyphrase,
      });
      if (formRef.current) {
        const input = formRef.current.querySelector(
          'input[type="text"], input[type="search"], input:not([type])'
        ) as HTMLInputElement;
        if (input) {
          input.value = keyphrase;
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [keyphrase, onKeyphraseChange]);

  const keyphraseHandler = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const target = event.target;
      const value = target.value;
      setInputValue(value);
      onInputChange?.(value);
      onKeyphraseChange({
        keyphrase: value,
      });
    },
    [onKeyphraseChange, onInputChange]
  );

  const handleSuggestionClick = useCallback(
    (suggestionText: string) => {
      setInputValue(suggestionText);
      onInputChange?.(suggestionText);
      onKeyphraseChange({
        keyphrase: suggestionText,
      });
      if (formRef.current) {
        const input = formRef.current.querySelector(
          'input[type="text"], input[type="search"], input:not([type])'
        ) as HTMLInputElement;
        if (input) {
          input.value = suggestionText;
          const inputEvent = new Event('input', { bubbles: true });
          input.dispatchEvent(inputEvent);
          const changeEvent = new Event('change', { bubbles: true });
          input.dispatchEvent(changeEvent);
        }
        if (submitRedirectionHandler) {
          submitRedirectionHandler(suggestionText, activeFilterParams);
        } else {
          formRef.current.requestSubmit();
        }
      }
    },
    [onKeyphraseChange, onInputChange, submitRedirectionHandler, activeFilterParams]
  );

  const handleClearInput = useCallback(() => {
    setInputValue('');
    onInputChange?.('');
    onKeyphraseChange({ keyphrase: '' });
    submitRedirectionHandler?.('');
  }, [onKeyphraseChange, onInputChange, submitRedirectionHandler]);

  return (
    <div className={styles['preview-search-bar']}>
      <PreviewSearch.Root>
        <form
          ref={formRef}
          onSubmit={(e) => {
            e.preventDefault();
            const { value: query } = e.currentTarget.elements[0] as HTMLInputElement;
            setInputValue(query);
            onInputChange?.(query);
            if (submitRedirectionHandler) {
              submitRedirectionHandler(query, activeFilterParams);
            }
          }}
        >
          <PreviewSearch.Input
            onChange={keyphraseHandler}
            autoComplete="off"
            placeholder={placeholderText}
            className={inputClassName}
            value={inputValue}
          />
          <button
            type="button"
            onClick={handleClearInput}
            className={styles['preview-search-bar__clear-button']}
            aria-label={clearSearchAriaLabel}
            hidden={!hasMounted || !(widgetKeyphrase?.trim().length > 0)}
          >
            <MaterialIcon name="CloseOutlined" />
          </button>
          <button
            type="submit"
            aria-label={submitSearchAriaLabel}
            className={styles['preview-search-bar__submit-button']}
          >
            <MaterialIcon name="search" />
          </button>
        </form>
        <PreviewSearch.Content
          data-loading={loading}
          ref={widgetRef}
          className={cx('preview-search-bar__content', 'preview-search-bar__content-mobile')}
        >
          <Presence present={loading}>
            <div className={styles['preview-search-bar__skeleton']}>
              {matchedSite && (
                <Skeleton variant="rounded" height={32} sx={{ mx: 2, mt: 2, mb: 1 }} />
              )}
              {Array.from({ length: defaultItemsPerPage }, (_, i) => (
                <div key={i} className={styles['preview-search-bar__skeleton-row']}>
                  <Skeleton variant="circular" width={24} height={24} />
                  <Skeleton variant="text" sx={{ flex: 1 }} height={24} />
                </div>
              ))}
            </div>
          </Presence>
          <Presence present={!loading}>
            <div>
              {matchedSite && (
                <div className={styles['preview-search-bar__search-within']}>
                  <MaterialIcon name="ScreenSearchDesktopOutlined" />
                  <span className={styles['preview-search-bar__search-within-text']}>
                    {searchingPrefix}{' '}
                    <span>{isSearchingWithin ? matchedSite.name : searchingAllSiteName}</span>
                    <span className={styles['preview-search-bar__search-within-text']}>.</span>
                  </span>
                  <a
                    href="#"
                    onClick={(e) => {
                      e.preventDefault();
                      onToggleSearchWithin();
                    }}
                  >
                    {isSearchingWithin
                      ? searchAllInstead
                      : `${searchSiteInstead} ${matchedSite.name} ${searchSiteInsteadSuffix}`}
                  </a>
                </div>
              )}
              <PreviewSearch.Suggestions>
                {inputValue.length == 0 && (
                  <>
                    {showRecentSuggestions && recentHistorySuggestions.length > 0 && (
                      <SuggestionBlock
                        blockId={'recent_history'}
                        items={recentHistorySuggestions}
                        title={recentSuggestionsTitle}
                        disabled={true}
                        onSuggestionClick={handleSuggestionClick}
                        suggestionsClassName={styles['preview-search-bar__suggestion-block-recent']}
                        iconName={'AccessTimeOutlined'}
                      />
                    )}
                    {showRecentSuggestions &&
                      showTrendingSuggestions &&
                      recentHistorySuggestions.length > 0 &&
                      trendingTermsSuggestions.length > 0 && <hr />}
                    {showTrendingSuggestions && trendingTermsSuggestions.length > 0 && (
                      <SuggestionBlock
                        blockId={'trending_terms'}
                        items={trendingTermsSuggestions}
                        title={trendingSuggestionsTitle}
                        disabled={true}
                        onSuggestionClick={handleSuggestionClick}
                        suggestionsClassName={
                          styles['preview-search-bar__suggestion-block-buttons']
                        }
                      />
                    )}
                  </>
                )}
              </PreviewSearch.Suggestions>

              {inputValue && inputValue.length > 1 && (
                <>
                  {queryResult?.data?.content?.length === 0 && (
                    <h1>
                      {noSuggestionsFound} &quot;{inputValue}&quot;
                    </h1>
                  )}
                  <PreviewSearch.Results defaultQueryResult={queryResult}>
                    {({ data: { content: articles = [] } = {} }) => (
                      <PreviewSearch.Items>
                        {articles.map((article, index) => (
                          <PreviewSearch.Item key={article.id} asChild>
                            <PreviewSearch.ItemLink
                              href={article.url}
                              className={styles['preview-search-bar__item-link']}
                              onClick={() => {
                                onItemClick({
                                  id: article.id,
                                  index,
                                  sourceId: article.source_id,
                                });
                                if (itemRedirectionHandler) {
                                  itemRedirectionHandler(article);
                                }
                              }}
                            >
                              <ArticleCard.Root>
                                <section>
                                  <ArticleCard.Title
                                    className={styles['preview-search-bar__item-title']}
                                  >
                                    <MaterialIcon
                                      name={getResultTypeIcon(article)}
                                      className="relative"
                                    />
                                    {article.name || article.title}
                                  </ArticleCard.Title>
                                </section>
                              </ArticleCard.Root>
                            </PreviewSearch.ItemLink>
                          </PreviewSearch.Item>
                        ))}
                      </PreviewSearch.Items>
                    )}
                  </PreviewSearch.Results>
                </>
              )}
            </div>
          </Presence>
        </PreviewSearch.Content>
      </PreviewSearch.Root>
    </div>
  );
};

const SearchBarInnerWidget = widget(SearchBarInner, WidgetDataType.PREVIEW_SEARCH, 'content');

export const GlobalSearchBarWidget = ({
  showSearchWithin = true,
  keyphrase: externalKeyphrase,
  rfkId,
  ...props
}: PreviewSearchBarProps & { rfkId?: string }) => {
  const { matchedSite, searchWithinQueryString } = useSearchWithinSite(showSearchWithin);
  const [isSearchingWithin, setIsSearchingWithin] = useState(true);
  const [liftedInput, setLiftedInput] = useState(externalKeyphrase || '');

  useEffect(() => {
    if (externalKeyphrase !== undefined) {
      setLiftedInput(externalKeyphrase);
    }
  }, [externalKeyphrase]);

  const activeSearchWithin = isSearchingWithin && !!matchedSite;

  return (
    <SearchBarInnerWidget
      rfkId={rfkId || 'content'}
      {...props}
      keyphrase={liftedInput}
      matchedSite={showSearchWithin ? matchedSite : null}
      isSearchingWithin={activeSearchWithin}
      onToggleSearchWithin={() => setIsSearchingWithin((prev) => !prev)}
      onInputChange={setLiftedInput}
      searchWithinQueryString={searchWithinQueryString}
    />
  );
};

export default GlobalSearchBarWidget;
