// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 14:55:19 GMT-0500 (Eastern Standard Time)

import classNames from 'classnames/bind';
import { MaterialIcon } from 'components/common/Icon/MaterialIcon';
import SuggestionBlock from 'components/search/components/SuggestionBlock';
import { ContentEntityModel } from 'components/search/models/content-entity';
import type { ChangeEvent } from 'react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { WidgetDataType, usePreviewSearch, widget, FilterAnd } from '@sitecore-search/react';
import { useGatedVisibilityFilter } from 'components/search/hooks/useGatedVisibilityFilter';
import { buildEmbargoFilter } from 'src/lib/sitecore-search/filters/embargo-filter';
import { ArticleCard, Presence, PreviewSearch } from '@sitecore-search/ui';
import Skeleton from '@mui/material/Skeleton';
import type { PreviewSearchInitialState } from '@sitecore-search/react';

const cx = classNames.bind(styles);

import styles from './styles.module.scss';

type InitialState = PreviewSearchInitialState<'keyphrase' | 'itemsPerPage' | 'suggestionsList'>;
interface PreviewSearchBarProps {
  defaultItemsPerPage: number | 6;
  placeholder?: string;
  inputClassName?: string;
  keyphrase?: string;

  /**
   * An optional custom redirection handler that will be called when the user clicks on an article.
   * You can use your own redirection logic here, or any other side effect.
   * Examples
   * * (article: Article) => history.push(`/search?q=${article.id}`);
   * * (article: Article) => window.location.href = `/search?q=${article.id}`;
   * * (article: Article) => setRoute(`/custom/search/endpoint?q=${article.id}`);
   * @param article The article that was clicked.
   */
  itemRedirectionHandler?: (article: ContentEntityModel) => void;

  /**
   * An optional custom submit handler that will be called when the user submits the form by pressing the enter key.
   * You can use your own submit logic here, or any other side effect.
   * Most common use case is to redirect the user to a custom search page with the query string.
   * Examples
   * * (query: string) => history.push(`/search?q=${query}`);
   * * (query: string) => window.location.href = `/search?q=${query}`;
   * * (query: string) => setRoute(`/custom/search/endpoint?q=${query}`);
   * @param query The query string that was submitted.
   */
  submitRedirectionHandler?: (query: string) => void;
  displaySuggestions?: boolean;
  displayPreviewSearchResults?: boolean;
  displayCloseButton?: boolean;
}
export const PreviewSearchBarComponent = ({
  defaultItemsPerPage = 6,
  placeholder = 'Search for policies, news, benefits...',
  inputClassName,
  keyphrase,
  itemRedirectionHandler,
  submitRedirectionHandler,
  displaySuggestions = true,
  displayPreviewSearchResults = true,
  displayCloseButton = false,
}: PreviewSearchBarProps) => {
  const gatedVisibilityFilter = useGatedVisibilityFilter();
  const searchFilter = useMemo(
    () => new FilterAnd([gatedVisibilityFilter, buildEmbargoFilter()]),
    [gatedVisibilityFilter]
  );

  const {
    widgetRef,
    actions: { onItemClick, onKeyphraseChange },
    query: searchQuery,
    queryResult,
    queryResult: {
      isFetching,
      isLoading,
      data: { suggestion: { title_context_aware: articleSuggestions = [] } = {} } = {},
    },
  } = usePreviewSearch<ContentEntityModel, InitialState>({
    state: {
      keyphrase: keyphrase || '',
      suggestionsList: [
        {
          suggestion: 'title_context_aware',
          max: 3,
        },
      ],
      itemsPerPage: defaultItemsPerPage,
    },
  });
  const loading = isLoading || isFetching;
  const formRef = useRef<HTMLFormElement>(null);
  const [inputValue, setInputValue] = useState<string>(keyphrase || '');

  useEffect(() => {
    searchQuery.getRequest().setSearchFilter(searchFilter);
  }, [searchFilter, searchQuery]);

  useEffect(() => {
    if (keyphrase !== undefined && keyphrase !== inputValue) {
      setInputValue(keyphrase);
      onKeyphraseChange({
        keyphrase: keyphrase,
      });
      // Also update the input element directly if it exists
      if (formRef.current) {
        const input = formRef.current.querySelector(
          'input[type="text"], input[type="search"], input:not([type])'
        ) as HTMLInputElement;
        if (input) {
          input.value = keyphrase;
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [keyphrase, onKeyphraseChange]);

  const keyphraseHandler = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      const target = event.target;
      const value = target.value;
      setInputValue(value);
      onKeyphraseChange({
        keyphrase: value,
      });
    },
    [onKeyphraseChange]
  );

  const handleClearInput = useCallback(() => {
    setInputValue('');
    onKeyphraseChange({ keyphrase: '' });
    submitRedirectionHandler?.('');
  }, [onKeyphraseChange, submitRedirectionHandler]);

  // Handler for suggestion clicks that updates the input value and submits the form
  const handleSuggestionClick = useCallback(
    (suggestionText: string) => {
      // Update the keyphrase in the widget state
      onKeyphraseChange({
        keyphrase: suggestionText,
      });
      // Update the input value directly by finding the input element in the form
      if (formRef.current) {
        const input = formRef.current.querySelector(
          'input[type="text"], input[type="search"], input:not([type])'
        ) as HTMLInputElement;
        if (input) {
          input.value = suggestionText;
          // Trigger input event to ensure PreviewSearch updates
          const inputEvent = new Event('input', { bubbles: true });
          input.dispatchEvent(inputEvent);
          // Also trigger change event
          const changeEvent = new Event('change', { bubbles: true });
          input.dispatchEvent(changeEvent);
        }
        // Submit the form
        if (submitRedirectionHandler) {
          submitRedirectionHandler(suggestionText);
        } else {
          // Fallback to native form submission
          formRef.current.requestSubmit();
        }
      }
    },
    [onKeyphraseChange, submitRedirectionHandler]
  );
  return (
    <div className={styles['preview-search-bar']}>
      <PreviewSearch.Root>
        <form
          ref={formRef}
          onSubmit={(e) => {
            e.preventDefault();
            const { value: query } = e.currentTarget.elements[0] as HTMLInputElement;
            if (submitRedirectionHandler) {
              submitRedirectionHandler(query);
            }
          }}
        >
          <PreviewSearch.Input
            onChange={keyphraseHandler}
            autoComplete="off"
            placeholder={placeholder}
            className={inputClassName}
            value={inputValue}
          />
          {displayCloseButton && inputValue?.trim().length > 0 && (
            <button
              type="button"
              onClick={handleClearInput}
              className={styles['preview-search-bar__clear-button']}
              aria-label="Clear search"
            >
              <MaterialIcon name="CloseOutlined" />
            </button>
          )}
          <button
            type="submit"
            aria-label="Submit search"
            className={styles['preview-search-bar__submit-button']}
          >
            <MaterialIcon name="search" />
          </button>
        </form>
        {(displaySuggestions || displayPreviewSearchResults) && (
          <PreviewSearch.Content
            data-loading={loading}
            ref={widgetRef}
            className={cx('preview-search-bar__content')}
          >
            <Presence present={loading}>
              <Skeleton variant="text" sx={{ width: '100%' }} height={40} />
            </Presence>
            <Presence present={!loading}>
              <div>
                {displaySuggestions && articleSuggestions.length > 0 && (
                  <PreviewSearch.Suggestions>
                    <SuggestionBlock
                      blockId={'title_context_aware'}
                      items={articleSuggestions}
                      title={'Suggestions'}
                      disabled={true}
                      onSuggestionClick={handleSuggestionClick}
                    />
                  </PreviewSearch.Suggestions>
                )}
                {displayPreviewSearchResults && (
                  <PreviewSearch.Results defaultQueryResult={queryResult}>
                    {({ data: { content: articles = [] } = {} }) => (
                      <PreviewSearch.Items>
                        {articles.map((article, index) => (
                          <PreviewSearch.Item key={article.id} asChild>
                            <PreviewSearch.ItemLink
                              href={article.url}
                              className={styles['preview-search-bar__item-link']}
                              onClick={() => {
                                // onItemClick is for tracking purposes
                                onItemClick({
                                  id: article.id,
                                  index,
                                  sourceId: article.source_id,
                                });
                                if (itemRedirectionHandler) {
                                  itemRedirectionHandler(article);
                                }
                              }}
                            >
                              <ArticleCard.Root>
                                <section>
                                  <ArticleCard.Title
                                    className={styles['preview-search-bar__item-title']}
                                  >
                                    {article.name || article.title}
                                  </ArticleCard.Title>
                                </section>
                              </ArticleCard.Root>
                            </PreviewSearch.ItemLink>
                          </PreviewSearch.Item>
                        ))}
                      </PreviewSearch.Items>
                    )}
                  </PreviewSearch.Results>
                )}
              </div>
            </Presence>
          </PreviewSearch.Content>
        )}
      </PreviewSearch.Root>
    </div>
  );
};
const PreviewSearchBarWidget = widget(
  PreviewSearchBarComponent,
  WidgetDataType.PREVIEW_SEARCH,
  'content'
);
export default PreviewSearchBarWidget;
