---
ID: "e4e75d05-a2a4-4a03-90c4-e42cdd590b47"
Parent: "1d1601e8-8679-4277-8130-46bd57d9a058"
Template: "bed31d6f-d968-45a9-b54e-12d7f977d861"
Path: /sitecore/system/Settings/Feature/Intralox/Product Segment/Product Segment Headless Site Setup
SharedFields:
- ID: "40deee2f-7595-40bd-b2c9-51f9e2346100"
  Hint: Dependencies
  Value: "{24EC97FA-F22A-404E-BC39-9B0673D46271}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4df0433d-eb47-407c-adae-ca4c1a81ca32"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260523T065215Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fc3b98b0-0bdd-4469-a04e-e7715d292d19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Product Segment
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260523T065340Z
