---
ID: "9f033b97-ab9b-44c0-bf07-7edb2a82e699"
Parent: "2b4b681c-2221-4503-b5c2-44a645c7ec28"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Intralox/Call to Action/Rendering Parameters/Call to Action Parameters/CTA Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260311T095949Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "df27f188-84ed-4904-aea9-0b3bf62dcf94"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260325T141923Z
