// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItems: number;
  totalItemsReturned: number;
};
const QueryResultsSummary = ({ totalItems }: QueryResultsSummaryProps) => {
  return (
    <div>
      {/* Showing {itemsPerPage * (currentPage - 1) + 1} - {itemsPerPage * (currentPage - 1) + totalItemsReturned} of{' '} */}
      {totalItems} results
    </div>
  );
};
export default QueryResultsSummary;
