---
ID: "13d050ef-7015-4d49-a3fb-9bbb550fe8bc"
Parent: "3b2f7d51-9bdb-4ed9-8c19-cc8ff8c4bf31"
Template: "3b2f7d51-9bdb-4ed9-8c19-cc8ff8c4bf31"
Path: /sitecore/templates/Foundation/Intralox/Global Rendering Setting/Global Rendering Setting/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260424T082907Z
    - ID: "388f6149-0624-48ca-b798-79757cf7eb44"
      Hint: HasTopPadding
      Value: 1
    - ID: "40925d18-1129-4aab-b3bc-2ccb43dcc323"
      Hint: HasBottomPadding
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da4d4f29-f95f-4c1c-adc7-3cc0b6ee62c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260424T082917Z
