---
ID: "48686c2b-8c18-468a-8414-451c3b56d369"
Parent: "bed2643a-f67b-4c43-bb00-75dd13387d4e"
Template: "bed2643a-f67b-4c43-bb00-75dd13387d4e"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260210T090330Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eac32748-2707-4fff-b630-0d4df99735c8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.kumar@intralox.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260210T090330Z
