// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import {
  WidgetDataType,
  useSearchResults,
  widget,
  useSearchResultsActions,
  FilterAnd,
} from '@sitecore-search/react';
import { useI18n } from 'next-localization';
import { useState, useEffect, useMemo, useRef, useCallback } from 'react';

import type { SearchResultsInitialState, SearchResultsStoreState } from '@sitecore-search/react';
import type { SearchResultsStoreSelectedFacets } from '@sitecore-search/widgets';
import type { ActionProp, ItemClickedAction } from '@sitecore-search/core';

import { DailyReflectionListingStatics } from '../../../IntranetComponents/DailyReflectionListing/DailyReflectionListing.types';
import { useGatedVisibilityFilter } from '../../hooks/useGatedVisibilityFilter';
import { buildEmbargoFilter } from 'src/lib/sitecore-search/filters/embargo-filter';
import ReflectionSearchFacets from '../../components/ReflectionSearchFacets';
import ReflectionsSearchPagination from '../../components/ReflectionSearchPagination';
import styles from './styles.module.scss';

type ArticleModel = {
  id: string;
  author?: string;
  type?: string;
  title?: string;
  name?: string;
  subtitle?: string;
  url?: string;
  description?: string;
  content_text?: string;
  image_url?: string;
  source_id?: string;
  publishedDate?: string;
};

type RenderResultCardProps<T> = {
  item: T | null;
  index: number;
  onItemClick: ActionProp<ItemClickedAction>;
  isLoading: boolean;
};

type ReflectionListingSearchResultsProps<T = ArticleModel> = {
  defaultSortType: SearchResultsStoreState['sortType'];
  defaultPage?: SearchResultsStoreState['page'];
  defaultItemsPerPage?: SearchResultsStoreState['itemsPerPage'];
  defaultKeyphrase?: SearchResultsStoreState['keyphrase'];
  keyphrase?: SearchResultsStoreState['keyphrase'];
  renderResultCard: (props: RenderResultCardProps<T>) => React.JSX.Element;
  layoutMode?: 'grid' | 'row';
  showSortOrder?: boolean;
  clearKeyphrase?: () => void;
};

type InitialState = SearchResultsInitialState<
  'itemsPerPage' | 'keyphrase' | 'page' | 'sortType' | 'selectedFacets'
>;

export const ReflectionListingSearchResultsComponent = <T extends { id: string } = ArticleModel>({
  defaultSortType,
  defaultPage = 1,
  defaultKeyphrase = '',
  keyphrase: externalKeyphrase,
  defaultItemsPerPage = 7,
  renderResultCard,
  layoutMode = 'grid',
  clearKeyphrase,
}: ReflectionListingSearchResultsProps<T>) => {
  const [allArticles, setAllArticles] = useState<T[]>([]);
  const prevArticlesRef = useRef<T[]>([]);
  const { t } = useI18n();

  const dictionaryStatics = {
    resultsLabelSingular:
      t('DailyReflectionListingResultsLabelSingular') ||
      DailyReflectionListingStatics.ResultsLabelSingular,
    resultsLabelPlural:
      t('DailyReflectionListingResultsLabelPlural') ||
      DailyReflectionListingStatics.ResultsLabelPlural,
    resultsFor: t('DailyReflectionListingResultsFor') || DailyReflectionListingStatics.ResultsFor,
    noResultsFor:
      t('DailyReflectionListingNoResultsFor') || DailyReflectionListingStatics.NoResultsFor,
    clear: t('DailyReflectionListingClearText') || DailyReflectionListingStatics.Clear,
    emptyTitle: t('DailyReflectionListingEmptyTitle') || DailyReflectionListingStatics.EmptyTitle,
    emptyDescription:
      t('DailyReflectionListingEmptyDescription') || DailyReflectionListingStatics.EmptyDescription,
  };

  // Helper to read facets from query string (using lowercase labels)
  const getFacetsFromQueryString = useCallback(
    (availableFacets: typeof facets): SearchResultsStoreSelectedFacets => {
      if (typeof window === 'undefined') return [];

      const urlParams = new URLSearchParams(window.location.search);
      const facetMap: Record<string, string[]> = {};

      for (const [key, value] of urlParams.entries()) {
        if (key.startsWith('f.')) {
          const facetLabel = key.substring(2).toLowerCase();
          if (!facetMap[facetLabel]) {
            facetMap[facetLabel] = [];
          }
          facetMap[facetLabel].push(value.toLowerCase());
        }
      }

      // Convert lowercase labels to IDs by doing case-insensitive lookup in the facets response
      if (availableFacets.length === 0) return [];

      return Object.entries(facetMap).flatMap(([facetLabelLower, valueLabelsLower]) => {
        // Case-insensitive facet label match
        const facet = availableFacets.find((f) => f.label.toLowerCase() === facetLabelLower);
        if (!facet) return [];

        return valueLabelsLower
          .map((valueLabelLower) => {
            // Case-insensitive value label match
            const facetValue = facet.value.find((v) => v.text.toLowerCase() === valueLabelLower);
            if (!facetValue) return null;
            return {
              facetId: facet.name,
              facetValueId: facetValue.id,
            } as SearchResultsStoreSelectedFacets[number];
          })
          .filter((f): f is SearchResultsStoreSelectedFacets[number] => f !== null);
      });
    },
    []
  );
  const { onFacetClick } = useSearchResultsActions();
  const gatedVisibilityFilter = useGatedVisibilityFilter();
  const searchFilter = useMemo(
    () => new FilterAnd([gatedVisibilityFilter, buildEmbargoFilter()]),
    [gatedVisibilityFilter]
  );

  const {
    widgetRef,
    actions: { onKeyphraseChange, onItemClick, onClearFilters },
    query: searchQuery,
    state: { page, itemsPerPage, keyphrase, selectedFacets },
    queryResult: {
      isFetching,
      isLoading,
      data: { total_item: totalItems = 0, facet: facets = [], content: articles = [] } = {},
    },
  } = useSearchResults<T, InitialState>({
    query: (query) => {
      query.getRequest().setSearchFilter(searchFilter);
    },
    state: {
      sortType: defaultSortType,
      page: defaultPage,
      itemsPerPage: defaultItemsPerPage,
      keyphrase: defaultKeyphrase,
      selectedFacets: [], // Will be restored from query string after facets load
    },
  });

  // Reactively update the search filter (gated + embargo) when session loads
  useEffect(() => {
    searchQuery.getRequest().setSearchFilter(searchFilter);
  }, [searchFilter, searchQuery]);

  // Track previous keyphrase to detect changes
  const prevKeyphraseRef = useRef(keyphrase);
  // Track if we've done initial restoration
  const hasRestoredRef = useRef(false);

  // Accumulate articles from different pages
  useEffect(() => {
    if (articles && articles.length > 0) {
      // Get previous articles to avoid duplicates
      const prevArticles = prevArticlesRef.current;
      const newArticles = articles.filter(
        (article) => !prevArticles.some((prev) => prev.id === article.id)
      );

      if (newArticles.length > 0) {
        setAllArticles((prev) => [...prev, ...newArticles]);
        prevArticlesRef.current = articles;
      }
    }
  }, [articles]);

  // Reset accumulated articles when search or filters change
  useEffect(() => {
    setAllArticles([]);
    prevArticlesRef.current = [];
  }, [keyphrase, selectedFacets]);

  // Sync external keyphrase prop to widget state
  useEffect(() => {
    if (externalKeyphrase !== undefined && externalKeyphrase !== keyphrase) {
      prevKeyphraseRef.current = keyphrase;
      onKeyphraseChange({
        keyphrase: externalKeyphrase,
      });
    }
  }, [externalKeyphrase, keyphrase, onKeyphraseChange]);

  // Restore selectedFacets from query string after keyphrase change or initial load
  // Wait for search results to load so facet labels are available
  useEffect(() => {
    const keyphraseChanged = prevKeyphraseRef.current !== keyphrase;

    // Reset restoration flag when keyphrase changes so we can restore again
    if (keyphraseChanged) {
      hasRestoredRef.current = false;
    }

    prevKeyphraseRef.current = keyphrase;
    const isInitialLoad = !hasRestoredRef.current;

    // Restore if:
    // 1. Initial load (haven't restored yet) AND facets are loaded AND selectedFacets is empty, OR
    // 2. Keyphrase changed AND facets were cleared AND results have loaded
    // This prevents restoring when user intentionally deselects facets
    const shouldRestore =
      !isLoading &&
      !isFetching &&
      facets.length > 0 &&
      selectedFacets.length === 0 &&
      !hasRestoredRef.current &&
      (isInitialLoad || keyphraseChanged);

    if (shouldRestore) {
      const queryFacets = getFacetsFromQueryString(facets);
      // Mark as restored immediately to prevent query string sync from clearing it
      hasRestoredRef.current = true;

      if (queryFacets.length > 0) {
        // Facets exist in query string but not in widget state - restore them
        // Find matching facets in the response to get proper indices
        queryFacets.forEach((facet) => {
          if ('facetValueId' in facet && facet.facetValueId) {
            // Find the facet and value in the response to get correct indices
            const facetInResponse = facets.find((f) => f.name === facet.facetId);
            if (facetInResponse) {
              const valueIndex = facetInResponse.value.findIndex(
                (v) => v.id === facet.facetValueId
              );
              if (valueIndex >= 0) {
                const facetIndex = facets.findIndex((f) => f.name === facet.facetId);
                onFacetClick({
                  facetId: facet.facetId,
                  facetValueId: facet.facetValueId,
                  checked: true,
                  facetIndex,
                  facetValueIndex: valueIndex,
                  type: 'valueId',
                });
              }
            }
          }
        });
      }
    }
  }, [
    keyphrase,
    selectedFacets,
    onFacetClick,
    isLoading,
    isFetching,
    facets,
    getFacetsFromQueryString,
  ]);

  // Update query string when selectedFacets changes (using labels)
  // Skip if we haven't restored yet to avoid clearing the query string before restoration
  useEffect(() => {
    if (typeof window === 'undefined') return;

    // Don't clear query string if we haven't restored yet (might be restoring from URL)
    if (!hasRestoredRef.current && selectedFacets.length === 0) {
      return;
    }

    const urlParams = new URLSearchParams(window.location.search);

    // Remove all existing facet params
    const keysToRemove: string[] = [];
    for (const key of urlParams.keys()) {
      if (key.startsWith('f.')) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach((key) => urlParams.delete(key));

    // Add current selectedFacets using lowercase labels
    selectedFacets.forEach((facet) => {
      if ('facetValueId' in facet && facet.facetValueId) {
        // Use facetLabel and valueLabel if available, otherwise look them up
        let facetLabel: string | undefined = facet.facetLabel;
        let valueLabel: string | undefined = facet.valueLabel;

        if (!facetLabel || !valueLabel) {
          // Fallback: look up labels from facets response
          const facetInResponse = facets.find((f) => f.name === facet.facetId);
          if (facetInResponse) {
            const valueInResponse = facetInResponse.value.find((v) => v.id === facet.facetValueId);
            if (valueInResponse) {
              facetLabel = facetInResponse.label;
              valueLabel = valueInResponse.text;
            }
          }
        }

        if (facetLabel && valueLabel) {
          // Convert to lowercase for URL
          urlParams.append(`f.${facetLabel.toLowerCase()}`, valueLabel.toLowerCase());
        }
      }
    });

    const newUrl = `${window.location.pathname}?${urlParams.toString()}`;
    window.history.replaceState({}, '', newUrl);
  }, [selectedFacets, facets]);

  // On initial load without search, skip the first article (show articles 2-7 instead of 1-6)
  // Cap to page * 6 so "show more" also displays 6 items per batch (not 7)
  const isNoSearchMode = !keyphrase && selectedFacets.length === 0;
  const displayedArticles = isNoSearchMode
    ? allArticles.slice(1, 1 + page * 6)
    : allArticles.slice(0, page * 6);
  const hasResultsToShow = isNoSearchMode ? displayedArticles.length > 0 : totalItems > 0;

  const totalPages = Math.ceil(totalItems / itemsPerPage);

  return (
    <>
      {!isLoading && !isFetching && keyphrase && (
        <div className={styles['search-result-listing__results-summary']}>
          {totalItems > 0 ? (
            <span>
              {totalItems}{' '}
              {totalItems === 1
                ? dictionaryStatics.resultsLabelSingular
                : dictionaryStatics.resultsLabelPlural}{' '}
              {dictionaryStatics.resultsFor}{' '}
              <span className={styles['search-result-listing__results-summary-keyphrase']}>
                “{keyphrase}”
              </span>
            </span>
          ) : (
            <span>
              {dictionaryStatics.noResultsFor}{' '}
              <span className={styles['search-result-listing__results-summary-keyphrase']}>
                “{keyphrase}”
              </span>
            </span>
          )}
          <button
            type="button"
            className={styles['search-result-listing__results-summary-clear']}
            onClick={() => {
              onClearFilters();
              if (clearKeyphrase) {
                clearKeyphrase();
              }
            }}
          >
            {dictionaryStatics.clear}
          </button>
        </div>
      )}

      <div ref={widgetRef} className={styles['search-result-listing']}>
        {/* Main Content */}
        <div className={styles['search-result-listing__content']}>
          {/* Sidebar with Filters */}
          <aside
            className={`${styles['search-result-listing__sidebar']} ${styles['search-result-listing__sidebar--open']}`}
          >
            <div className={styles['search-result-listing__facets-container']}>
              <ReflectionSearchFacets facets={facets} />
            </div>
          </aside>

          {/* Main Content Area */}
          <div className={styles['search-result-listing__main']}>
            <>
              {hasResultsToShow || isLoading || isFetching ? (
                <>
                  {/* Results Grid */}
                  <div
                    className={`${styles['search-result-listing__grid']} ${
                      layoutMode === 'row' ? styles['search-result-listing__grid--row'] : ''
                    }`}
                  >
                    {(isLoading && displayedArticles.length === 0
                      ? [...Array(isNoSearchMode ? itemsPerPage - 1 : itemsPerPage)]
                      : displayedArticles
                    ).map((item, index) =>
                      renderResultCard({
                        item: isLoading && displayedArticles.length === 0 ? null : (item as T),
                        index,
                        onItemClick,
                        isLoading: isLoading && displayedArticles.length === 0,
                      })
                    )}
                  </div>

                  {/* Pagination */}
                  {!isLoading && !isFetching && hasResultsToShow && (
                    <div className={styles['search-result-listing__pagination-container']}>
                      <ReflectionsSearchPagination currentPage={page} totalPages={totalPages} />
                    </div>
                  )}
                </>
              ) : (
                <div className={styles['search-result-listing__empty-state']}>
                  <h3>{dictionaryStatics.emptyTitle}</h3>
                  <p>{dictionaryStatics.emptyDescription}</p>
                  <button
                    type="button"
                    className={styles['search-result-listing__results-summary-clear']}
                    onClick={() => {
                      onClearFilters();
                      if (clearKeyphrase) {
                        clearKeyphrase();
                      }
                    }}
                  >
                    {dictionaryStatics.clear}
                  </button>
                </div>
              )}
            </>
          </div>
        </div>
      </div>
    </>
  );
};

const ReflectionListingSearchResultsWidget = widget(
  ReflectionListingSearchResultsComponent,
  WidgetDataType.SEARCH_RESULTS,
  'content'
);

export default ReflectionListingSearchResultsWidget;
