// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import { ArrowLeftIcon, ArrowRightIcon } from '@radix-ui/react-icons';
import { useSearchResultsActions } from '@sitecore-search/react';
import { Pagination } from '@sitecore-search/ui';
import classNames from 'classnames/bind';
import type { RefObject } from 'react';
import styles from './styles.module.scss';

const cx = classNames.bind(styles);

type SearchPaginationProps = {
  currentPage: number;
  totalPages: number;
  scrollTargetRef?: RefObject<HTMLElement | null>;
};
const SearchPagination = ({ currentPage, totalPages, scrollTargetRef }: SearchPaginationProps) => {
  const { onPageNumberChange } = useSearchResultsActions();

  const handlePageChange = (page: number) => {
    onPageNumberChange({ page });
    scrollTargetRef?.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <div className={cx('search-pagination')}>
      <Pagination.Root
        currentPage={currentPage}
        defaultCurrentPage={1}
        totalPages={totalPages}
        onPageChange={handlePageChange}
      >
        <Pagination.PrevPage onClick={(_e) => _e.preventDefault()}>
          <ArrowLeftIcon />
        </Pagination.PrevPage>
        <Pagination.Pages>
          {(pagination) =>
            Pagination.paginationLayout(pagination, {
              boundaryCount: 1,
              siblingCount: 1,
            }).map(({ page, type }) =>
              type === 'page' ? (
                <Pagination.Page
                  key={page}
                  aria-label={`Page ${page}`}
                  page={page as number}
                  onClick={(_e) => _e.preventDefault()}
                >
                  {page}
                </Pagination.Page>
              ) : (
                <span key={type} className={cx('search-pagination__ellipsis')}>
                  ...
                </span>
              )
            )
          }
        </Pagination.Pages>
        <Pagination.NextPage onClick={(_e) => _e.preventDefault()}>
          <ArrowRightIcon />
        </Pagination.NextPage>
      </Pagination.Root>
    </div>
  );
};
export default SearchPagination;
