---
ID: "8cdfb26c-02f1-4def-ac4d-85b6af0a27f5"
Parent: "47879006-dd79-4c28-9c77-353a265f933f"
Template: "47879006-dd79-4c28-9c77-353a265f933f"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Products/Sprockets/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260511T094202Z
    - ID: "46107cb4-da05-4caa-95b8-5b1a0e466f36"
      Hint: Technology
      Value: "{5EAE3A7F-C63A-4A5E-9D11-4B9B39356E4B}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "86cd172e-1354-4222-a495-c84b13906220"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260603T110055Z
