---
ID: "948f1c57-f1bc-4149-a5b5-f6cf12b73a46"
Parent: "c01bae8a-bab1-42ab-b0b9-2e2fb28b5043"
Template: "c01bae8a-bab1-42ab-b0b9-2e2fb28b5043"
Path: /sitecore/templates/Feature/Customer Portal/Quote Detail/QuoteDetail/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "aeec6d08-dab9-4dd9-ab1d-6b3c01b81986"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0213ae67-d508-41d3-936f-8c28689c1b64"
      Hint: RequestDocumentButtonType
      Value: Request Document
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260507T064719Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9068874a-aaa9-4e0c-8079-4f178d00dd00"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260512T081818Z
