---
ID: "261e98f8-762f-4a50-b4fe-089112d3712f"
Parent: "426d8be0-72bb-4994-b31f-0a1ade627bd3"
Template: "426d8be0-72bb-4994-b31f-0a1ade627bd3"
Path: /sitecore/templates/Feature/Customer Portal/Auth/Rendering Parameters/Auth Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "504034d2-28cd-46e6-bc82-5c1f4b81e301"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251205T104147Z
