---
ID: "0d6f40fa-fe1d-4bbe-b85e-b53f7e9d90d4"
Parent: "4ce9073b-ca79-42b4-aab7-9cc77b63bbfc"
Template: "4ce9073b-ca79-42b4-aab7-9cc77b63bbfc"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Products/Belt Page/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "02af6b15-0f2c-4de0-aeb6-64b816b919a1"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "07ab541d-eeb5-4f91-b9f3-cba84d2888a2"
      Hint: ShowParentPage
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260429T103048Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a3a5d15-b82b-4732-af17-ec75c532f3d1"
    - ID: "b361baab-550e-4196-ae9c-ce8aba1bad94"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260511T144125Z
