// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 14:55:19 GMT-0500 (Eastern Standard Time)

import { usePreviewSearchActions } from '@sitecore-search/react';
import { PreviewSearch } from '@sitecore-search/ui';
import styles from './styles.module.scss';
import { MaterialIcon } from 'components/common/Icon/MaterialIcon';

type SuggestionBlockProps = {
  items: Array<{
    text: string;
  }>;
  title: string;
  blockId: string;
  filterAttribute?: string;
  disabled?: boolean;
  onSuggestionClick?: (suggestionText: string) => void;
  suggestionsClassName?: string;
  iconName?: string;
};
const SuggestionBlock = ({
  items,
  title,
  blockId,
  filterAttribute,
  disabled,
  onSuggestionClick: customOnSuggestionClick,
  suggestionsClassName,
  iconName,
}: SuggestionBlockProps) => {
  const { onSuggestionClick: defaultOnSuggestionClick } = usePreviewSearchActions();
  return (
    <>
      {items.length > 0 && (
        <PreviewSearch.SuggestionsGroup
          id={blockId}
          filterAttribute={filterAttribute}
          className={`${styles['suggestion-block__group']}`}
        >
          <h2 className={styles['suggestion-block__title']}>{title}</h2>
          <div className="flex flex-wrap gap-2">
            {items.map(({ text }) => (
              <PreviewSearch.SuggestionTrigger id={text} key={text} disabled={disabled} asChild>
                <a
                  className={`${styles['suggestion-block__link']} ${suggestionsClassName}`}
                  onClick={() => {
                    defaultOnSuggestionClick({
                      name: blockId,
                      title,
                      value: text,
                      displayName: text,
                    });
                    // Call custom handler if provided
                    if (customOnSuggestionClick) {
                      customOnSuggestionClick(text);
                    }
                  }}
                >
                  {iconName && (
                    <MaterialIcon name={iconName} className={styles['suggestion-block__icon']} />
                  )}
                  {text}
                </a>
              </PreviewSearch.SuggestionTrigger>
            ))}
          </div>
        </PreviewSearch.SuggestionsGroup>
      )}
    </>
  );
};
export default SuggestionBlock;
