// This component was generated by @sitecore-search/cli on Wed Dec 10 2025 12:38:03 GMT-0500 (Eastern Standard Time)

import {
  AccordionFacets,
  FacetItem,
  RangeFacet,
  SearchResultsAccordionFacets,
  SearchResultsFacetValueRange,
} from '@sitecore-search/ui';
import { useState, useEffect } from 'react';

import { CheckIcon } from '@radix-ui/react-icons';
import { useSearchResultsActions } from '@sitecore-search/react';
import type { SearchResponseFacet } from '@sitecore-search/react';

import styles from './styles.module.scss';

type SearchFacetsProps = {
  facets: SearchResponseFacet[];
  displayFacetValueCount?: boolean;
};
type PriceFacetProps = {
  min: number;
  max: number;
};
const PriceFacet = ({ min, max }: PriceFacetProps) => {
  return (
    <SearchResultsFacetValueRange max={max} min={min} autoAdjustValues={false}>
      <RangeFacet.Track>
        <RangeFacet.Range />
      </RangeFacet.Track>
      <RangeFacet.Start>{(value) => <span>${value}</span>}</RangeFacet.Start>
      <RangeFacet.End>{(value) => <span>${value}</span>}</RangeFacet.End>
    </SearchResultsFacetValueRange>
  );
};
const Facets = ({ facets, displayFacetValueCount = false }: SearchFacetsProps) => {
  const { onFacetClick } = useSearchResultsActions();
  // Expand only the first facet by default
  const [expandedList, setExpandedList] = useState<string[]>(() =>
    facets.length > 0 ? [facets[0].name] : []
  );

  // Update expanded list when facets change - preserve user's manual expand/collapse choices
  useEffect(() => {
    const facetNames = facets.map((facet) => facet.name);
    setExpandedList((prev) => {
      // Keep only facets that still exist in the new facet list
      const stillValid = prev.filter((name) => facetNames.includes(name));
      // If no valid expanded facets remain, expand the first one
      if (stillValid.length === 0 && facets.length > 0) {
        return [facets[0].name];
      }
      return stillValid;
    });
  }, [facets]);

  return (
    <div className={styles['search-facets']}>
      <SearchResultsAccordionFacets
        facetTypesExpandedList={expandedList}
        onFacetTypesExpandedListChange={setExpandedList}
        onFacetValueClick={onFacetClick}
      >
        {facets.map((facet) => (
          <AccordionFacets.Facet facetId={facet.name} key={facet.name}>
            <AccordionFacets.Header className={styles['search-facets__header']}>
              <AccordionFacets.Trigger className={styles['search-facets__header-trigger']}>
                {facet.label}
              </AccordionFacets.Trigger>
            </AccordionFacets.Header>
            <AccordionFacets.Content>
              <AccordionFacets.ValueList>
                {facet.name !== 'price' ? (
                  facet.value.map((facetValue, index) => (
                    <FacetItem
                      {...{
                        index,
                        facetValueId: facetValue.id,
                      }}
                      key={facetValue.id}
                    >
                      <AccordionFacets.ItemCheckbox>
                        <AccordionFacets.ItemCheckboxIndicator>
                          <CheckIcon />
                        </AccordionFacets.ItemCheckboxIndicator>
                      </AccordionFacets.ItemCheckbox>
                      <AccordionFacets.ItemLabel>
                        <span>{facetValue.text}</span>
                        {facetValue.count && displayFacetValueCount && (
                          <span className={styles['search-facets__count']}>{facetValue.count}</span>
                        )}
                      </AccordionFacets.ItemLabel>
                    </FacetItem>
                  ))
                ) : (
                  <PriceFacet
                    min={Math.floor(facet.value[0].min)}
                    max={Math.floor(facet.value[facet.value.length - 1].max)}
                  />
                )}
              </AccordionFacets.ValueList>
            </AccordionFacets.Content>
          </AccordionFacets.Facet>
        ))}
      </SearchResultsAccordionFacets>
    </div>
  );
};
export default Facets;
