---
ID: "092ea2d5-db09-466f-8296-4ce3106a5df5"
Parent: "ec34a747-1347-45f2-a502-5857084b8778"
Template: "ec34a747-1347-45f2-a502-5857084b8778"
Path: /sitecore/templates/Project/Corporate Sites/Intralox/Page Types/Policy Statements/Country Policy Statement/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "d39ed779-0dd9-44c8-a86c-7a656d5423fe"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260422T091540Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5de78976-b380-4eb7-8baa-f0b63cf75e29"
      Hint: ContainerWidth
      Value: "{7FD79BA7-7522-4E5E-8CDD-F5E564789F88}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ced63aa-b263-49a2-a0bd-6f13acfb0c08"
    - ID: "b03fc922-fce6-421b-8991-7333ff5fab7d"
      Hint: Title
      Value: Policy Statements
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260519T164255Z
