---
ID: "0febf41a-6030-4016-8407-ff46cfd22edc"
Parent: "e4ec1159-9634-43a7-9a0d-68033b879432"
Template: "e4ec1159-9634-43a7-9a0d-68033b879432"
Path: /sitecore/templates/Feature/Customer Portal/Featured Content/Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251204T102537Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\suneel.joshi@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\suneel.joshi@icreon.com
    - ID: "7b3da93d-a6b5-4b05-9cce-eab8a22ff61b"
      Hint: Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff3b8a46-e996-49cb-ae1c-52f883aa0c7e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\suneel.joshi@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251204T102546Z
