---
ID: "72a52473-5b47-4258-9883-5db5b60eb0bb"
Parent: "4a6012e7-c448-4177-a30a-348ad706c5a0"
Template: "4a6012e7-c448-4177-a30a-348ad706c5a0"
Path: /sitecore/templates/Feature/Customer Portal/Script Content/Rendering Parameters/ScriptContent Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b17c3d89-4e68-4c1f-b670-922d3f214206"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251211T104440Z
