---
ID: "fb6f4e1d-9b6a-478b-82fd-72e52a055001"
Parent: "d0c84237-f02d-4f9b-8eaf-a09286177cc2"
Template: "d0c84237-f02d-4f9b-8eaf-a09286177cc2"
Path: /sitecore/templates/Feature/Customer Portal/User Info/Rendering Parameters/UserInfo Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1b6524af-65e7-408d-93f3-ffe56f1e69b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\deepanshu.badge@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260507T113123Z
