---
ID: "7b73df03-97b7-4d02-82b6-ef3ea7dcccf1"
Parent: "9747f9f4-67d0-481b-a3b9-9d5f7c4b3c96"
Template: "9747f9f4-67d0-481b-a3b9-9d5f7c4b3c96"
Path: /sitecore/templates/Foundation/Intralox/Products/File/__Standard Values
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "68836790-4273-45ef-9fa7-1f8edc93c586"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260509T094115Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "57b62399-193c-4ec4-b09f-e9ecfa13b76b"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce0874e6-318a-4353-8a3c-bd9cc98008fc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260526T071532Z
