---
ID: "fed26501-115d-45e2-b7f6-cf58049fbfab"
Parent: "c2cfbe1c-6d71-4ab9-a454-fa28ae199ddd"
Template: "c2cfbe1c-6d71-4ab9-a454-fa28ae199ddd"
Path: /sitecore/templates/Feature/Intralox/FAQ/FAQ Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E2AECE58-8D3D-4A75-B604-C83BC5E0587F}
    {C2CFBE1C-6D71-4AB9-A454-FA28AE199DDD}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "2c4cb25a-49a7-4730-917d-5ed298bfba04"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "377ac3c5-30a8-47a7-a8b0-9dac5ae885dc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shivani.dogra@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260326T053755Z
