---
ID: "27ab5c76-ff2e-46d8-b7ab-71235db09b7e"
Parent: "4c58d2b8-92f2-463d-8f9e-4dbabad261c0"
Template: "4c58d2b8-92f2-463d-8f9e-4dbabad261c0"
Path: /sitecore/templates/Foundation/Intralox/Products/Belt Identifier Type/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8065ff87-c73a-4e78-9686-87293e014d48"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260508T104827Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arun.k@icreon.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1801034f-6b4c-44ba-86ce-4fe8125018f5"
    - ID: "b46517df-78ac-4116-87e1-4b13ad5023a1"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\shubham.lekhi@icreon.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260530T134340Z
